service: line-bot-sawayaka-ikitai
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-1
  deploymentBucket: serverless-upload-ap-northeast-1
  versionFunctions: false

functions:
  callback:
    handler: handler.callback
    events:
      - http:
          path: callback
          method: post
    environment:
      LINE_ACCESS_TOKEN: "${ssm:/line/dia/access_token~true}"
      LINE_CHANNEL_SECRET: "${ssm:/line/dia/channel_secret~true}"

resources:
  Description: ruby-chan want to go sawayaka
  Resources:
    ## override
    CallbackLogGroup:
      Properties:
        RetentionInDays: 7

    ## dns setting
    Domain:
      Type: AWS::ApiGateway::DomainName
      Properties:
        CertificateArn: "${ssm:/acm/camelon.info~true}"
        DomainName: "sawayaka.camelon.info"

    Mapping:
      Type: AWS::ApiGateway::BasePathMapping
      Properties:
        DomainName: { Ref: Domain }
        RestApiId:  { Ref: ApiGatewayRestApi }
        Stage: dev

    RecordSetOfAPI:
      Type: AWS::Route53::RecordSet
      Properties:
        Name: "sawayaka.camelon.info"
        Type: A
        HostedZoneName: "camelon.info."
        AliasTarget:
          DNSName: { Fn::GetAtt: [Domain, DistributionDomainName] }
          HostedZoneId: Z2FDTNDATAQYW2
